import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useAsyncError,
  useLocation,
  useRouteError,
} from 'react-router';

import { useButton } from '@react-aria/button';
import {
  type CSSProperties,
  Component,
  type FC,
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react';
import './global.css';

// @ts-expect-error -- virtual module generated by Vite plugin at build time
import { LoadFonts } from 'virtual:load-fonts.jsx';
import fetch from '@/__create/fetch';
// @ts-expect-error -- generated auth module, no type declarations available
import { SessionProvider } from '@auth/create/react';
import { toPng } from 'html-to-image';
import { useNavigate } from 'react-router';
import { serializeError } from 'serialize-error';
import { Toaster, toast } from 'sonner';
import { useDevServerHeartbeat } from '../__create/useDevServerHeartbeat';
import '../__create/design-mode';
import type { Route } from './+types/root';

export const links = () => [];

const criticalFallbackCss = `
  :root {
    --color-surface: #ffffff;
    --color-soft: #fafafa;
    --color-ink: #111111;
    --color-muted: #6b7280;
    --color-line: #f3f4f6;
    --color-accent: #b45309;
    --font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    --font-serif: Georgia, Cambria, "Times New Roman", Times, serif;
  }
  *, *::before, *::after { box-sizing: border-box; }
  html, body { width: 100%; min-width: 0; margin: 0; overflow-x: hidden; background: var(--color-surface); color: var(--color-ink); font-family: var(--font-sans); }
  img, video, canvas, svg { max-width: 100%; }
  img, video { display: block; }
  a { color: inherit; text-decoration: none; }
  button, input { font: inherit; }
  .app-shell, .min-h-screen { min-height: 100svh; }
  .bg-white { background: #fff; }
  .bg-black { background: #000; }
  .bg-transparent { background: transparent; }
  .bg-\\[\\#fafafa\\] { background: #fafafa; }
  .bg-gray-50 { background: #f9fafb; }
  .bg-gray-100 { background: #f3f4f6; }
  .bg-gray-200 { background: #e5e7eb; }
  .relative { position: relative; }
  .absolute { position: absolute; }
  .fixed { position: fixed; }
  .sticky { position: sticky; }
  .inset-0 { inset: 0; }
  .top-0 { top: 0; }
  .left-0 { left: 0; }
  .right-0 { right: 0; }
  .bottom-4 { bottom: 1rem; }
  .top-\\[72px\\] { top: 72px; }
  .z-20 { z-index: 20; }
  .z-30 { z-index: 30; }
  .z-50 { z-index: 50; }
  .overflow-hidden { overflow: hidden; }
  .overflow-x-auto { overflow-x: auto; }
  .w-full { width: 100%; }
  .w-8 { width: 2rem; }
  .w-10 { width: 2.5rem; }
  .w-24 { width: 6rem; }
  .w-\\[80\\%\\] { width: 80%; }
  .w-\\[80px\\] { width: 80px; }
  .h-full { height: 100%; }
  .h-3 { height: .75rem; }
  .h-8 { height: 2rem; }
  .h-10 { height: 2.5rem; }
  .h-24 { height: 6rem; }
  .h-28 { height: 7rem; }
  .h-px { height: 1px; }
  .h-\\[80vh\\] { height: 80vh; }
  .max-w-7xl { max-width: 80rem; }
  .max-w-4xl { max-width: 56rem; }
  .max-w-3xl { max-width: 48rem; }
  .max-w-2xl { max-width: 42rem; }
  .max-w-\\[80px\\] { max-width: 80px; }
  .mx-auto { margin-left: auto; margin-right: auto; }
  .block { display: block; }
  .inline-flex { display: inline-flex; }
  .flex { display: flex; }
  .grid { display: grid; }
  .hidden { display: none; }
  .flex-col { flex-direction: column; }
  .flex-wrap { flex-wrap: wrap; }
  .flex-1 { flex: 1 1 0%; }
  .shrink-0 { flex-shrink: 0; }
  .items-center { align-items: center; }
  .items-start { align-items: flex-start; }
  .justify-center { justify-content: center; }
  .justify-between { justify-content: space-between; }
  .text-center { text-align: center; }
  .text-left { text-align: left; }
  .object-cover { object-fit: cover; }
  .object-top { object-position: top; }
  .aspect-square { aspect-ratio: 1 / 1; }
  .aspect-video { aspect-ratio: 16 / 9; }
  .aspect-\\[3\\/4\\] { aspect-ratio: 3 / 4; }
  .aspect-\\[16\\/10\\] { aspect-ratio: 16 / 10; }
  .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
  .grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
  .grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
  .gap-3 { gap: .75rem; }
  .gap-4 { gap: 1rem; }
  .gap-8 { gap: 2rem; }
  .gap-12 { gap: 3rem; }
  .gap-20 { gap: 5rem; }
  .gap-24 { gap: 6rem; }
  .gap-x-8 { column-gap: 2rem; }
  .gap-y-16 { row-gap: 4rem; }
  .space-y-4 > :not([hidden]) ~ :not([hidden]) { margin-top: 1rem; }
  .space-y-3 > :not([hidden]) ~ :not([hidden]) { margin-top: .75rem; }
  .space-y-6 > :not([hidden]) ~ :not([hidden]) { margin-top: 1.5rem; }
  .space-y-8 > :not([hidden]) ~ :not([hidden]) { margin-top: 2rem; }
  .space-y-12 > :not([hidden]) ~ :not([hidden]) { margin-top: 3rem; }
  .space-y-16 > :not([hidden]) ~ :not([hidden]) { margin-top: 4rem; }
  .space-y-32 > :not([hidden]) ~ :not([hidden]) { margin-top: 8rem; }
  .space-x-2 > :not([hidden]) ~ :not([hidden]) { margin-left: .5rem; }
  .space-x-3 > :not([hidden]) ~ :not([hidden]) { margin-left: .75rem; }
  .space-x-4 > :not([hidden]) ~ :not([hidden]) { margin-left: 1rem; }
  .space-x-6 > :not([hidden]) ~ :not([hidden]) { margin-left: 1.5rem; }
  .space-x-8 > :not([hidden]) ~ :not([hidden]) { margin-left: 2rem; }
  .p-10 { padding: 2.5rem; }
  .p-12 { padding: 3rem; }
  .p-2 { padding: .5rem; }
  .px-4 { padding-left: 1rem; padding-right: 1rem; }
  .px-6 { padding-left: 1.5rem; padding-right: 1.5rem; }
  .px-8 { padding-left: 2rem; padding-right: 2rem; }
  .px-10 { padding-left: 2.5rem; padding-right: 2.5rem; }
  .px-12 { padding-left: 3rem; padding-right: 3rem; }
  .py-2 { padding-top: .5rem; padding-bottom: .5rem; }
  .py-3 { padding-top: .75rem; padding-bottom: .75rem; }
  .py-4 { padding-top: 1rem; padding-bottom: 1rem; }
  .py-5 { padding-top: 1.25rem; padding-bottom: 1.25rem; }
  .py-6 { padding-top: 1.5rem; padding-bottom: 1.5rem; }
  .py-7 { padding-top: 1.75rem; padding-bottom: 1.75rem; }
  .py-20 { padding-top: 5rem; padding-bottom: 5rem; }
  .py-32 { padding-top: 8rem; padding-bottom: 8rem; }
  .py-40 { padding-top: 10rem; padding-bottom: 10rem; }
  .pt-32 { padding-top: 8rem; }
  .pt-40 { padding-top: 10rem; }
  .pt-10 { padding-top: 2.5rem; }
  .pt-20 { padding-top: 5rem; }
  .pb-10 { padding-bottom: 2.5rem; }
  .pb-20 { padding-bottom: 5rem; }
  .pb-32 { padding-bottom: 8rem; }
  .mt-1 { margin-top: .25rem; }
  .mt-2 { margin-top: .5rem; }
  .mt-4 { margin-top: 1rem; }
  .mt-6 { margin-top: 1.5rem; }
  .mt-12 { margin-top: 3rem; }
  .mr-auto { margin-right: auto; }
  .mb-1 { margin-bottom: .25rem; }
  .mb-2 { margin-bottom: .5rem; }
  .mb-3 { margin-bottom: .75rem; }
  .mb-4 { margin-bottom: 1rem; }
  .mb-6 { margin-bottom: 1.5rem; }
  .mb-8 { margin-bottom: 2rem; }
  .mb-10 { margin-bottom: 2.5rem; }
  .mb-12 { margin-bottom: 3rem; }
  .mb-16 { margin-bottom: 4rem; }
  .mb-20 { margin-bottom: 5rem; }
  .border { border: 1px solid #e5e7eb; }
  .border-b { border-bottom: 1px solid #e5e7eb; }
  .border-t { border-top: 1px solid #e5e7eb; }
  .border-gray-50 { border-color: #f9fafb; }
  .border-gray-100 { border-color: #f3f4f6; }
  .border-gray-200 { border-color: #e5e7eb; }
  .border-black { border-color: #000; }
  .shadow-sm { box-shadow: 0 1px 2px rgba(0, 0, 0, .05); }
  .rounded-full { border-radius: 9999px; }
  .text-white { color: #fff; }
  .text-black { color: #000; }
  .text-gray-300 { color: #d1d5db; }
  .text-gray-400 { color: #9ca3af; }
  .text-gray-500 { color: #6b7280; }
  .text-gray-600 { color: #4b5563; }
  .text-amber-600 { color: #d97706; }
  .text-amber-700 { color: #b45309; }
  .font-serif { font-family: var(--font-serif); }
  .font-light { font-weight: 300; }
  .font-medium { font-weight: 500; }
  .font-semibold { font-weight: 600; }
  .font-bold { font-weight: 700; }
  .italic { font-style: italic; }
  .uppercase { text-transform: uppercase; }
  .tracking-wide { letter-spacing: .025em; }
  .tracking-widest { letter-spacing: .1em; }
  .leading-relaxed { line-height: 1.625; }
  .leading-loose { line-height: 2; }
  .text-\\[8px\\] { font-size: 8px; }
  .text-\\[9px\\] { font-size: 9px; }
  .text-\\[10px\\] { font-size: 10px; }
  .text-xs { font-size: .75rem; line-height: 1rem; }
  .text-sm { font-size: .875rem; line-height: 1.25rem; }
  .text-lg { font-size: 1.125rem; line-height: 1.75rem; }
  .text-xl { font-size: 1.25rem; line-height: 1.75rem; }
  .text-2xl { font-size: 1.5rem; line-height: 2rem; }
  .text-3xl { font-size: 1.875rem; line-height: 2.25rem; }
  .text-4xl { font-size: 2.25rem; line-height: 2.5rem; }
  .text-5xl { font-size: 3rem; line-height: 1; }
  .tracking-\\[0\\.2em\\] { letter-spacing: .2em; }
  .tracking-\\[0\\.3em\\] { letter-spacing: .3em; }
  .tracking-\\[0\\.4em\\] { letter-spacing: .4em; }
  .tracking-\\[0\\.6em\\] { letter-spacing: .6em; }
  .transition-all, .transition-colors, .transition-transform, .transition-opacity { transition-duration: 200ms; }
  .duration-700 { transition-duration: 700ms; }
  .duration-1000 { transition-duration: 1000ms; }
  .group:hover .group-hover\\:scale-105 { transform: scale(1.05); }
  .group:hover .group-hover\\:scale-110 { transform: scale(1.1); }
  .group:hover .group-hover\\:opacity-100 { opacity: 1; }
  .opacity-0 { opacity: 0; }
  .opacity-80 { opacity: .8; }
  .opacity-100 { opacity: 1; }
  .translate-y-2 { transform: translateY(.5rem); }
  .-translate-x-1\\/2 { transform: translateX(-50%); }
  .site-navbar { position: fixed; top: 0; left: 0; width: 100%; z-index: 50; transition: all .5s ease; }
  .site-navbar__inner { width: 100%; padding-inline: clamp(1rem, 4vw, 4rem); min-height: 2.75rem; display: flex; align-items: center; justify-content: space-between; }
  .site-navbar__brand { position: absolute; left: 50%; transform: translateX(-50%); color: #111; line-height: 1; white-space: nowrap; font-family: var(--font-serif); font-size: clamp(1rem, 2.2vw, 1.5rem); letter-spacing: .3em; font-weight: 300; text-transform: uppercase; }
  .site-navbar__actions { display: flex; align-items: center; gap: 1.5rem; flex-shrink: 0; }
  .home-editorial__tile, .home-editorial__strip { background: #f3f4f6; }
  .home-editorial__image { display: block; width: 100%; height: 100%; object-fit: cover; object-position: center; }
  .home-editorial__image--seated { object-position: center 56%; }
  .home-editorial__image--jacket { object-position: center 46%; }
  .home-editorial__image--portrait { object-position: center 42%; }
  .home-editorial__image--red-full { object-position: center 46%; }
  .home-editorial__image--red-horizontal { object-position: center 54%; }
  .home-editorial__image--jacket-close { object-position: center 36%; }
  .home-editorial__image--door { object-position: center 70%; }
  .home-editorial-pair { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 3px; background: #fff; }
  .home-editorial-pair__panel { position: relative; min-height: clamp(30rem, 76vh, 54rem); overflow: hidden; background: #f3f4f6; }
  .home-editorial-pair__panel--video { background: #000; }
  .home-editorial-pair__media { display: block; width: 100%; height: 100%; min-height: inherit; object-fit: cover; }
  .home-editorial-pair__image { object-position: center 64%; }
  .home-editorial-pair__quote { right: clamp(1.5rem, 4vw, 4rem); bottom: clamp(1.5rem, 4vw, 4rem); }
  .home-portfolio__card { min-height: clamp(26rem, 45vw, 31.25rem); }
  @media (max-width: 767px) {
    .home-editorial-pair { grid-template-columns: 1fr; }
    .home-editorial-pair__panel { min-height: clamp(22rem, 95vw, 34rem); }
    .home-editorial-pair__image { object-position: center 72%; }
  }
  @media (min-width: 640px) {
    .sm\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .sm\\:flex-row { flex-direction: row; }
    .sm\\:space-x-4 > :not([hidden]) ~ :not([hidden]) { margin-left: 1rem; }
    .sm\\:space-y-0 > :not([hidden]) ~ :not([hidden]) { margin-top: 0; }
  }
  @media (min-width: 768px) {
    .md\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .md\\:grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    .md\\:text-5xl { font-size: 3rem; line-height: 1; }
    .md\\:text-7xl { font-size: 4.5rem; line-height: 1; }
    .md\\:flex-row { flex-direction: row; }
    .md\\:items-center { align-items: center; }
    .md\\:space-x-0 > :not([hidden]) ~ :not([hidden]) { margin-left: 0; }
    .md\\:space-y-0 > :not([hidden]) ~ :not([hidden]) { margin-top: 0; }
    .md\\:col-span-2 { grid-column: span 2 / span 2; }
    .md\\:block { display: block; }
    .md\\:mt-0 { margin-top: 0; }
  }
  @media (min-width: 1024px) {
    .lg\\:flex { display: flex; }
    .lg\\:hidden { display: none; }
    .lg\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .lg\\:grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    .lg\\:grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
    .lg\\:col-span-1 { grid-column: span 1 / span 1; }
    .lg\\:col-span-2 { grid-column: span 2 / span 2; }
    .lg\\:w-1\\/2 { width: 50%; }
    .lg\\:flex-row { flex-direction: row; }
    .lg\\:flex-row-reverse { flex-direction: row-reverse; }
    .lg\\:gap-24 { gap: 6rem; }
    .lg\\:px-16 { padding-left: 4rem; padding-right: 4rem; }
  }
  @media (min-width: 1280px) {
    .xl\\:grid-cols-4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
  }
`;

if (globalThis.window && globalThis.window !== undefined) {
  globalThis.window.fetch = fetch;
}

const LoadFontsSSR = import.meta.env.SSR ? LoadFonts : null;
if (import.meta.hot) {
  import.meta.hot.on('update-font-links', (urls: string[]) => {
    // remove old font links
    for (const link of document.querySelectorAll('link[data-auto-font]')) {
      link.remove();
    }

    // add new ones
    for (const url of urls) {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = url;
      link.dataset.autoFont = 'true';
      document.head.appendChild(link);
    }
  });
}

function InternalErrorBoundary({ error: errorArg }: Route.ErrorBoundaryProps) {
  const routeError = useRouteError();
  const asyncError = useAsyncError();
  const error = errorArg ?? asyncError ?? routeError;
  const [isOpen, setIsOpen] = useState(false);
  const shouldScale = typeof window !== 'undefined' ? window.innerWidth < 768 : false;
  const scaleFactor = shouldScale ? 1.02 : 1;
  const copyButtonTextClass = shouldScale ? 'text-sm' : 'text-xs';
  const copyButtonPaddingClass = shouldScale ? 'px-[10px] py-[5px]' : 'px-[6px] py-[3px]';
  const postCountRef = useRef(0);
  const lastPostTimeRef = useRef(0);
  const lastErrorKeyRef = useRef<string | null>(null);
  const MAX_ERROR_POSTS_PER_ERROR = 5;
  const THROTTLE_MS = 1000;

  useEffect(() => {
    const serialized = serializeError(error);
    const errorKey = JSON.stringify(serialized);

    // Reset the counter when a genuinely different error arrives
    if (errorKey !== lastErrorKeyRef.current) {
      lastErrorKeyRef.current = errorKey;
      postCountRef.current = 0;
    }

    if (postCountRef.current >= MAX_ERROR_POSTS_PER_ERROR) {
      return;
    }

    const now = Date.now();
    const timeSinceLastPost = now - lastPostTimeRef.current;

    const post = () => {
      if (postCountRef.current >= MAX_ERROR_POSTS_PER_ERROR) {
        return;
      }
      postCountRef.current += 1;
      lastPostTimeRef.current = Date.now();
      window.parent.postMessage({ type: 'sandbox:error:detected', error: serialized }, '*');
    };

    if (timeSinceLastPost < THROTTLE_MS) {
      const timer = setTimeout(post, THROTTLE_MS - timeSinceLastPost);
      return () => clearTimeout(timer);
    }

    post();
  }, [error]);

  useEffect(() => {
    const animateTimer = setTimeout(() => setIsOpen(true), 100);
    return () => clearTimeout(animateTimer);
  }, []);
  const { buttonProps: copyButtonProps } = useButton(
    {
      onPress: useCallback(() => {
        const toastScale = shouldScale ? 1.2 : 1;
        const toastStyle = {
          padding: `${16 * toastScale}px`,
          background: '#18191B',
          border: '1px solid #2C2D2F',
          color: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
          width: `${280 * toastScale}px`,
          fontSize: `${13 * toastScale}px`,
          display: 'flex',
          alignItems: 'center',
          gap: `${6 * toastScale}px`,
          justifyContent: 'flex-start',
          margin: '0 auto',
        };
        navigator.clipboard.writeText(JSON.stringify(serializeError(error)));
        toast.custom(
          () => (
            <div style={toastStyle}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                height="20"
                width="20"
              >
                <title>Success</title>
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
                  clipRule="evenodd"
                />
              </svg>
              <span>Copied successfully!</span>
            </div>
          ),
          {
            id: 'copy-error-success',
            duration: 3000,
          }
        );
      }, [error, shouldScale]),
    },
    useRef<HTMLButtonElement>(null)
  );

  function isInIframe() {
    try {
      return window.parent !== window;
    } catch {
      return true;
    }
  }
  return (
    <>
      {!isInIframe() && (
        <div
          className={`fixed bottom-4 left-1/2 transform -translate-x-1/2 max-w-md z-50 transition-all duration-500 ease-out ${
            isOpen ? 'translate-y-0 opacity-100' : 'translate-y-full opacity-0'
          }`}
          style={{ width: '75vw' }}
        >
          <div
            className="bg-[#18191B] text-[#F2F2F2] rounded-lg p-4 shadow-lg w-full"
            style={
              scaleFactor !== 1
                ? ({
                    transform: `scale(${scaleFactor})`,
                    transformOrigin: 'bottom center',
                  } as CSSProperties)
                : undefined
            }
          >
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0">
                <div className="w-8 h-8 bg-[#F2F2F2] rounded-full flex items-center justify-center">
                  <span className="text-black text-[1.125rem] leading-none">!</span>
                </div>
              </div>

              <div className="flex flex-col gap-2 flex-1">
                <div className="flex flex-col gap-1">
                  <p className="font-light text-[#F2F2F2] text-sm">App Error Detected</p>
                  <p className="text-[#959697] text-sm font-light">
                    It looks like an error occurred while trying to use your app.
                  </p>
                </div>

                <button
                  className={`flex flex-row items-center justify-center gap-[4px] outline-none transition-colors rounded-[8px] border-[1px] bg-[#2C2D2F] hover:bg-[#414243] active:bg-[#555658] border-[#414243] text-white ${copyButtonTextClass} ${copyButtonPaddingClass} w-fit`}
                  type="button"
                  {...copyButtonProps}
                >
                  Copy error
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

type ErrorBoundaryProps = {
  children: React.ReactNode;
};

type ErrorBoundaryState = { hasError: boolean; error: unknown | null };

class ErrorBoundaryWrapper extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: unknown, info: unknown) {
    console.error(error, info);
  }

  render() {
    if (this.state.hasError) {
      return <InternalErrorBoundary error={this.state.error} params={{}} />;
    }
    return this.props.children;
  }
}

function LoaderWrapper({ loader }: { loader: () => React.ReactNode }) {
  return <>{loader()}</>;
}

type ClientOnlyProps = {
  loader: () => React.ReactNode;
};

export const ClientOnly: React.FC<ClientOnlyProps> = ({ loader }) => {
  // ErrorBoundaryWrapper sits outside the isMounted gate so it commits on
  // the first (empty) render and is a stable ancestor by the time children
  // mount. Catastrophic errors (e.g. stack overflow in user code) can blow
  // the call stack before React commits a boundary mounted in the same pass
  // as the throwing child; keeping the boundary always-mounted avoids that.
  return (
    <ErrorBoundaryWrapper>
      <LoaderWrapper loader={loader} />
    </ErrorBoundaryWrapper>
  );
};

/**
 * useHmrConnection()
 * ------------------
 * • `true`  → HMR socket is healthy
 * • `false` → socket lost (Vite is polling / may auto‑reload soon)
 *
 * Works only in dev; in prod it always returns `true`.
 */
export function useHmrConnection(): boolean {
  const [connected, setConnected] = useState(() => !!import.meta.hot);

  useEffect(() => {
    // No HMR object outside dev builds
    if (!import.meta.hot) return;

    /** Fired the moment the WS closes unexpectedly */
    const onDisconnect = () => setConnected(false);
    /** Fired every time the WS (re‑)opens */
    const onConnect = () => setConnected(true);

    import.meta.hot.on('vite:ws:disconnect', onDisconnect);
    import.meta.hot.on('vite:ws:connect', onConnect);

    // Optional: catch the “about to full‑reload” event as a last resort
    const onFullReload = () => setConnected(false);
    import.meta.hot.on('vite:beforeFullReload', onFullReload);

    return () => {
      import.meta.hot?.off('vite:ws:disconnect', onDisconnect);
      import.meta.hot?.off('vite:ws:connect', onConnect);
      import.meta.hot?.off('vite:beforeFullReload', onFullReload);
    };
  }, []);

  return connected;
}

const healthyResponseType = 'sandbox:web:healthcheck:response';
const useHandshakeParent = () => {
  const isHmrConnected = useHmrConnection();
  useEffect(() => {
    const healthyResponse = {
      type: healthyResponseType,
      healthy: isHmrConnected,
      supportsErrorDetected: true,
    };
    const handleMessage = (event: MessageEvent) => {
      if (event.data.type === 'sandbox:web:healthcheck') {
        window.parent.postMessage(healthyResponse, '*');
      }
    };
    window.addEventListener('message', handleMessage);
    // Immediately respond to the parent window with a healthy response in
    // case we missed the healthcheck message
    window.parent.postMessage(healthyResponse, '*');
    return () => {
      window.removeEventListener('message', handleMessage);
    };
  }, [isHmrConnected]);
};

const waitForScreenshotReady = async () => {
  const images = Array.from(document.images);

  await Promise.all([
    // make sure custom fonts are loaded
    'fonts' in document ? document.fonts.ready : Promise.resolve(),
    ...images.map(
      (img) =>
        new Promise((resolve) => {
          img.crossOrigin = 'anonymous';
          if (img.complete) {
            resolve(true);
            return;
          }
          img.onload = () => resolve(true);
          img.onerror = () => resolve(true);
        })
    ),
  ]);

  // small buffer to ensure rendering is stable
  await new Promise((resolve) => setTimeout(resolve, 250));
};

export const useHandleScreenshotRequest = () => {
  useEffect(() => {
    const handleMessage = async (event: MessageEvent) => {
      if (event.data.type === 'sandbox:web:screenshot:request') {
        try {
          await waitForScreenshotReady();

          const width = window.innerWidth;
          const aspectRatio = 16 / 9;
          const height = Math.floor(width / aspectRatio);

          // html-to-image already handles CORS, fonts, and CSS inlining
          const dataUrl = await toPng(document.body, {
            cacheBust: true,
            skipFonts: false,
            width,
            height,
            style: {
              // force snapshot sizing
              width: `${width}px`,
              height: `${height}px`,
              margin: '0',
            },
          });

          window.parent.postMessage({ type: 'sandbox:web:screenshot:response', dataUrl }, '*');
        } catch (error) {
          window.parent.postMessage(
            {
              type: 'sandbox:web:screenshot:error',
              error: error instanceof Error ? error.message : String(error),
            },
            '*'
          );
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => {
      window.removeEventListener('message', handleMessage);
    };
  }, []);
};
export function Layout({ children }: { children: ReactNode }) {
  useHandshakeParent();
  useHandleScreenshotRequest();
  useDevServerHeartbeat();
  const navigate = useNavigate();
  const location = useLocation();
  const pathname = location?.pathname;
  const isMobile = typeof window !== 'undefined' ? window.innerWidth < 768 : false;
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data.type === 'sandbox:navigation') {
        navigate(event.data.pathname);
      }
    };
    window.addEventListener('message', handleMessage);
    window.parent.postMessage({ type: 'sandbox:web:ready' }, '*');
    return () => {
      window.removeEventListener('message', handleMessage);
    };
  }, [navigate]);

  useEffect(() => {
    if (pathname) {
      window.parent.postMessage(
        {
          type: 'sandbox:web:navigation',
          pathname,
        },
        '*'
      );
    }
  }, [pathname]);
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content"
        />
        <Meta />
        <style data-critical-fallback dangerouslySetInnerHTML={{ __html: criticalFallbackCss }} />
        <Links />
        <script type="module" src="/src/__create/dev-error-overlay.js"></script>
        <link rel="icon" href="/src/__create/favicon.png" />
        {LoadFontsSSR ? <LoadFontsSSR /> : null}
      </head>
      <body>
        <ClientOnly loader={() => children} />
        <Toaster position={isMobile ? 'top-center' : 'bottom-right'} />
        <ScrollRestoration />
        <Scripts />
        <link rel="preconnect" href="https://ka-p.fontawesome.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href="https://ka-p.fontawesome.com/releases/v6.3.0/css/pro.min.css?token=2c15cc0cc7" crossOrigin="anonymous" />
      </body>
    </html>
  );
}

export const ErrorBoundary = InternalErrorBoundary;

export default function App() {
  return (
    <SessionProvider>
      <Outlet />
    </SessionProvider>
  );
}
